/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_adder_28 (
    input [2:0] a,
    input [2:0] b,
    input [5:0] alufn,
    output reg [2:0] sum
  );
  
  
  
  reg [2:0] summ;
  
  always @* begin
    
    case (alufn[0+0-:1])
      1'h1: begin
        summ = a - b;
      end
      1'h0: begin
        summ = a + b;
      end
      default: begin
        summ = 8'h00;
      end
    endcase
    sum = summ;
  end
endmodule
